### ISSUE TITLE
Open API 中的 TODO 事项

### ISSUE THREAD

**Issue by weizhenye** [bangumi/api#10]
0. Bangumi API 本身的版本为必填项，怎么填？
1. 文档中 `/user/:username/collection` 的 `cat` 参数 required 未打钩，实际不传的话不返回数据，应该是必填项？
2. 目前 `api.yml` 里按 `/subject/:subject_id` 的 responseGroup 给条目定义了三个模型 SubjectSmall、SubjectMedium、SubjectLarge。但下列接口返回的条目数据都比 SubjectSmall 还小（没有 `rating` 和 `rank`，`summary` 永远为空，有些缺少 `eps_count` 字段，`air_date` 和 `air_weekday` 数据也没的）：
    * `/user/:username/collection`
    * `/user/:username/collections/:subject_type`
    * `/user/:username/collections/status`
    * `/subject/:subject_id/ep`

    能否确定一个最小模型，至少包含的字段？
3. `/user/:username/progress` 返回的 `css_name` 是指什么？
4. ~~`/subject/:subject_id/update/watched_eps` 文档中 `watched_eps` 是 required，`watched_vols` 不是，应该是必填其一吧？~~
5. SubjectLarge 里 blog 的 image 是什么意思？日志中的第一张？

**Comment by OpportunityLiu** [comment]
-2. 还有 `/calendar`， `summary` 也是空的，`collection` 里面只有 `doing` 一项
-4. 有 `watched_vols` 必有 `watched_eps` 的吧
    ![image](https://user-images.githubusercontent.com/13471233/36829109-791ab908-1d58-11e8-80f6-41f2231e00c6.png)两者都有
    ![image](https://user-images.githubusercontent.com/13471233/36829166-caf0af1c-1d58-11e8-90d6-6cd3e2f70e17.png)只有 `watched_eps`

**Comment by ainopara** [comment]
刚刚试了下，可以单独只更新 vol 进度。

**Comment by Sai** [comment]
1. 应该是 required
2. 最小的应该包含 id / url / type / name 
3. 本来是给前端用的，这个是历史 API 不太好改字段名
5. 是的
