### ISSUE TITLE
post_collection 方法 不传入参数时 能否不将其改为默认值而是不做更改?

### ISSUE THREAD

**Issue by rin996** [bangumi/api#108]
当前[post_collection](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/post_collection__subject_id___action_)方法 如果不传rating tags score 等参数,会将其重置为空,但很多情况下 我们只想修改其中一项,我们需要将数据请求一次才能修改,很不方便.业界规范也普遍为传入哪个参数就修改哪个.希望能修改API.

**Comment by KiedaTamashi** [comment]
复议～
题外话，业界有很多需要全量修改的难用API （x

**Comment by Trim21** [comment]
会直接做新API的，旧API不再更新了
