### ISSUE TITLE
批量更新收藏进度失效

### ISSUE THREAD

**Issue by JamesYuuu** [bangumi/api#135]
使用命令curl -X 'POST' \
  'https://api.bgm.tv/subject/235612/update/watched_eps?watched_eps=13' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer access_token' \
  -d ''
返回{"request":"\/subject\/343656\/update\/watched_eps?watched_eps=9","code":202,"error":"Accepted"}
但实际上收视进度并未更新。

**Comment by Trim21** [comment]
旧API的bug不修了
