### ISSUE TITLE
[feature request]收藏列表请求需要带上条目信息

### ISSUE THREAD

**Issue by ekibun** [bangumi/api#141]
最好所有列表请求都能做成联表查询的形式

要实现收藏列表功能至少要加上
条目名称 简介 用户最近格子周围的100条ep数据 这100个ep的用户观看情况

**Comment by Trim21** [comment]
条目收藏的api加上条目信息，但是章节的信息就没必要再带上了吧。

**Comment by ekibun** [comment]
> 

那获取章节列表的api就要加上收藏情况。
要实现主页的效果，在收藏列表还要有最后一个格子的序号（方便定位分页）
另外我不建议全放上去，数据太多了

**Comment by Trim21** [comment]
要实现主页的效果的话想的是直接做个 API 按照现在的首页给数据。

**Comment by czy0729** [comment]
因为假如请求100个limit, 返回数据长度太大了, 超过1M, 而且每次都返回
建议条目数据也不是经常变化, 默认不返回, 带参数才返回, 我APP炸掉了
