### ISSUE TITLE
[feature request] 目前收藏列表请求带上的条目信息, 建议默认不返回

### ISSUE THREAD

**Issue by czy0729** [bangumi/api#143]
因为假如请求100个limit, 返回数据长度太大了, 超过1M, 而且每次都返回, 失去了数据解耦的优势
为了好用也是需要条目信息的, 建议默认不返回, 需要的时候才带上参数控制返回

**Comment by Trim21** [comment]
应该直接搞个graphql的。

先暂时删了一部分字段。

**Comment by czy0729** [comment]
你接口代码错了，现在name和name_cn都是日文。
collection_total数目也没对，希望是返回在看数量。

**Comment by czy0729** [comment]
接口提交的代码应该有问题，现在name和name_cn都是日文。
collection_total数目感觉也没对, 这个数字没有跟任何一个状态或总和对得上, 我目前需要的是在看数量。
@Trim21

**Comment by Trim21** [comment]
collection total是全部收藏人数

**Comment by czy0729** [comment]
@Trim21 这个 name_cn 又变成 日文了

**Comment by Trim21** [comment]
…我看看
