### ISSUE TITLE
/v0/episodes 返回格式不对

### ISSUE THREAD

**Issue by kookxiang** [bangumi/api#146]
- https://api.bgm.tv/v0/episodes?subject_id=326869
- https://api.bgm.tv/v0/episodes/1110274

这两个接口的返回格式应该是一样的

![image](https://user-images.githubusercontent.com/2725379/179540178-c94232b8-d732-4b12-92f1-c72c2e033442.png)

**Comment by Trim21** [comment]
不小心返回错了（

**Comment by Ukenn2112** [comment]
有毛病行为

**Comment by Ukenn2112** [comment]
> 不小心返回错了（

现在又是单集的 episodes/{episode_id} 返回错了。。
