### ISSUE TITLE
希望获取用户收藏的API，能够返回用户收藏条目的时间

### ISSUE THREAD

**Issue by fyzl233** [bangumi/api#151]
管理员大大们好，我是来自中国人民大学的学生。想利用bangumi的API进行基于动态图神经网络的推荐系统研究。研究的目标有（1）探索动画社区深度用户和浅度用户的区别，（2）做一个实时可用的动画个性化推荐系统。目前bangumi的API似乎只能获取到"updated_at"时间数据。据观察，似乎这个时间代表的是用户最后一次更新收视进度[点格子]的时间。不知能否返回用户收藏条目的时间，便于研究和应用，谢谢~

**Comment by Trim21** [comment]
数据库里没存...
