### ISSUE TITLE
调用api 批量更新收视进度 会清空已有进度

### ISSUE THREAD

**Issue by MooRoakee** [bangumi/api#158]
/subject/{subject_id}/update/watched_eps 批量更新收视进度调用无效 且会清空已有进度

以enage kiss为例, subject_id-375817:

![图片](https://user-images.githubusercontent.com/25135228/188307098-021523ef-87bf-400e-9da0-b23d07d434cf.png)

调用批量更新api之前的进度情况：

![图片](https://user-images.githubusercontent.com/25135228/188307138-73067cf2-01b9-4356-9884-8e96c34690d8.png)

使用postman进行接口调用， 预期结果为更新观看进度至p10：

![图片](https://user-images.githubusercontent.com/25135228/188307196-663c46c9-32d8-4ecb-9c53-c7c4266b9ea9.png)

实际调用结果 进度被清空: 

![图片](https://user-images.githubusercontent.com/25135228/188308118-d6695c14-3f90-4815-aae4-5f49f2d8a385.png)

**Comment by Trim21** [comment]
建议用新API

**Comment by MooRoakee** [comment]
原来这个是旧api么，请问新api文档地址是什么呢，感谢大佬

**Comment by Trim21** [comment]
https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserSubjectEpisodeCollection
