### ISSUE TITLE
部分接口为啥没有挂在 /v0 路径下

### ISSUE THREAD

**Issue by RanKKI** [bangumi/api#160]
比如 /search 和 /calendar，是有什么特殊设计？

我是想着一般 API 接口自从进入生产环境，如果有增加删除字段，应当让版本 +1，
按照我的理解，如果 /calendar 要进行修改，会直接影响到所有生产环境上调用该接口的 App

**Comment by Trim21** [comment]
`/search` 和 `/calendar` 是最一开始sai老板写的 API，有版本前缀的是开源在 https://github.com/bangumi/server 的新代码库提供的 API，现在是两套程序都在运行。

**Comment by Trim21** [comment]
增加字段不会break客户端，不会加版本号，要删字段会改版本号。

**Comment by RanKKI** [comment]
> `/search` 和 `/calendar` 是最一开始sai老板写的 API，有版本前缀的是开源在 https://github.com/bangumi/server 的新代码库提供的 API，现在是两套程序都在运行。

收到🫡，有机会改下文档吧（对项目还不熟，就不提 PR 了


> 增加字段不会break客户端，不会加版本号，要删字段会改版本号。

我是感觉增加字段应该也加版本号，不过确实不会影响客户端.
