### ISSUE TITLE
Patch /v0/users/-/collections/{subject_id}/episodes把p1从未看更新至已看时报错500

### ISSUE THREAD

**Issue by MooRoakee** [bangumi/api#161]
初始状态
![图片](https://user-images.githubusercontent.com/25135228/190443636-632ea93b-9517-4052-92a9-cc4e2ceb2d49.png)

想调用Patch /v0/users/-/collections/{subject_id}/episodes更新p1为已看
```
https://api.bgm.tv/v0/users/-/collections/309311/episodes

{
  "episode_id": [
    960324
  ],
  "type": 2
}
```
结果：报错
```
{
    "title": "Internal Server Error",
    "details": {
        "error": "failed to update episode: UpdateEpisodeCollection: dal: record not found",
        "path": "/v0/users/-/collections/309311/episodes",
        "method": "PATCH"
    },
    "description": "Unexpected Internal Server Error"
}
```

---
p1已看后再调接口更新别的剧集的观看状态就能成功

如果p1为已看 想更新p2从未看至已看
![图片](https://user-images.githubusercontent.com/25135228/190444618-b32ddf28-0376-4683-aad5-051ee5cd8cd0.png)
```
https://api.bgm.tv/v0/users/-/collections/309311/episodes

{
  "episode_id": [
    960325
  ],
  "type": 2
}
```
结果：成功
![图片](https://user-images.githubusercontent.com/25135228/190445504-77e343c9-00c4-4134-bb41-af6e6c3d177a.png)

**Comment by trim21** [comment]
这个bug已经修了，不过sai老板最近比较忙，没法给需要的数据库权限
