### ISSUE TITLE
PATCH /v0/users/-/collections/{subject_id} 无法修改 private 属性

### ISSUE THREAD

**Issue by zhangyoufu** [bangumi/api#162]
返回 204，但是 private 属性没有任何变化

**Comment by trim21** [comment]
有敏感词？

**Comment by zhangyoufu** [comment]
> 有敏感词？

没有涉及到敏感词

尝试了在同一个请求中修改 comment、tags 都能成功修改，但是 private 无法修改，也没有报错

**Comment by trim21** [comment]
可能你的comment有敏感词，在comment为空的情况下也没法修改private属性吗

**Comment by zhangyoufu** [comment]
> 可能你的comment有敏感词，在comment为空的情况下也没法修改private属性吗

`comment`为空的情况下也无法修改`private`属性

例如
```
curl -X PATCH "https://api.bgm.tv/v0/users/-/collections/$SUBJECT_ID" -H "Authorization: Bearer $ACCESS_TOKEN" -H 'Content-Type: application/json' -d '{"private": true}'
```

**Comment by trim21** [comment]
咦，我看看

**Comment by trim21** [comment]
tag呢，tag里也没有敏感词吗

**Comment by zhangyoufu** [comment]
> 也就是说这个收藏的原本就没有评论也没有tag，但是无法修改private状态是吧

是的

**Comment by zhangyoufu** [comment]
我感觉你把逻辑写反了

**Comment by zhangyoufu** [comment]
https://github.com/bangumi/server/blob/128358bc17e26e9626a80255fdc7b4fde04e0802/internal/ctrl/update_subject_collection.go#L61-L65

**Comment by trim21** [comment]
我也发现了，但这样设置private: true的时候应该能修改成所有人可见的，而不是像你说的无法修改属性。

晚上看看

**Comment by zhangyoufu** [comment]
是我的表述不对，我的操作都是 `private: true`，没有看到变化让我觉得无法修改。尝试用 `private: false` 后符合预期了

**Comment by trim21** [comment]
😂也不是你表述的问题，是我想当然了，因为经常有帖子问为什么收藏被标记成了私有没法解除，就以为是类似的情况
