### ISSUE TITLE
字段命名不统一

### ISSUE THREAD

**Issue by RanKKI** [bangumi/api#165]
`subjects/<sub_id>` 的字段名为 `date`，`search/<keyword>` 的是 `air_date`。

kookxiang/jellyfin-plugin-bangumi#31

**Comment by trim21** [comment]
完整的路径是啥...

**Comment by trim21** [comment]
如果是 /v0/subjects/<> 和 /search/ 的话就不改了，万一再break了别的用户

**Comment by RanKKI** [comment]
> 如果是 /v0/subjects/<> 和 /search/<> 的话就不改了，万一再break了别的用户

嗯嗯，确实是这俩，提 issue 的时候忘记带完整路径了。
