### ISSUE TITLE
官方API返回大量错误信息

### ISSUE THREAD

**Issue by realsuxingyu** [bangumi/api#166]
subject_id  16242
例如上面的条目  

[![xMCWB4.md.png](https://s1.ax1x.com/2022/10/02/xMCWB4.md.png)](https://imgse.com/i/xMCWB4)
标记数居然返回了这么大的一个数字

还有至少有数千次的其他请求内容明显错误

**Comment by realsuxingyu** [comment]
以上问题从数天前就发生了
今天做数据汇总的时候发现非常诡异
各种数据的sum非常异常 subject rate 全部sum 居然有三亿  一查居然很多条目返回标记数量几千万
还有查询735000以后的用户居然也有返回 不过是随机的另外一个用户

**Comment by realsuxingyu** [comment]
[![xMCXHH.md.png](https://s1.ax1x.com/2022/10/02/xMCXHH.md.png)](https://imgse.com/i/xMCXHH)
核实无误 请管理员看看是怎么一回事

**Comment by trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/193445742-4cbb0e50-73aa-4045-85e7-be8fc674c17d.png)
![image](https://user-images.githubusercontent.com/13553903/193445745-b6269b2b-07b0-43d7-88b5-41ffa4ac5862.png)
无法复现

**Comment by trim21** [comment]
也可能是cache的问题，我一会禁用下试试。

**Comment by realsuxingyu** [comment]
[![xM8seJ.md.png](https://s1.ax1x.com/2022/10/02/xM8seJ.md.png)](https://imgse.com/i/xM8seJ)
[![xM86oR.md.png](https://s1.ax1x.com/2022/10/02/xM86oR.md.png)](https://imgse.com/i/xM86oR)

我看了看日日志  返回的数值确实完整来自服务器 应该是你数据库内存撞了或者是什么原因吧
不过不是持续性的
可能哪里有些问题 你可以查一查日志

**Comment by realsuxingyu** [comment]
至于官网多个uid返回一个username和超出正常访问的uid返回随机正常uid
这个就比较无解了
因为只是最后一天出现的现象、如果是我代码问题不可能前几天一直正常
更神奇的是接下来又自动正常了  
由于冗余没做到位 也没天天备份  
导致我现在修复usertable真的是很痛苦（bgm38）
[![xM8oeH.md.png](https://s1.ax1x.com/2022/10/02/xM8oeH.md.png)](https://imgse.com/i/xM8oeH)
[![xM87TA.md.png](https://s1.ax1x.com/2022/10/02/xM87TA.md.png)](https://imgse.com/i/xM87TA)
[![xM8qYt.md.png](https://s1.ax1x.com/2022/10/02/xM8qYt.md.png)](https://imgse.com/i/xM8qYt)

**Comment by trim21** [comment]
收藏人数这个是老bug。

我再看看user ID的问题

**Comment by realsuxingyu** [comment]
[![xMGlfx.md.png](https://s1.ax1x.com/2022/10/02/xMGlfx.md.png)](https://imgse.com/i/xMGlfx)
看看这张表 着实很诡异

**Comment by realsuxingyu** [comment]
还有想确认下 最近一个星期api调用量和主站数据库连接量明显增大了么？
MySQL connection error 是爬虫的锅么？
有没有添加什么限制措施？

**Comment by trim21** [comment]
爬API对数据库影响不太大，爬主站影响很大。

**Comment by trim21** [comment]
爬主站爬太快就会造成MySQL connection error

**Comment by realsuxingyu** [comment]
102011
101968
等一批user很奇怪、怎么请求api都是报错
为什么会有这种连状态都没有的用户？

**Comment by trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/193454551-6405099c-df4f-4ea1-bf8d-16405f63bbf3.png)
无法复现

**Comment by realsuxingyu** [comment]
@trim21  那你看看第一个uid

**Comment by trim21** [comment]
404 not found

**Comment by realsuxingyu** [comment]
bgm不是会显示[用户已注销] [已封禁]这种的么  为什么会404 not found
https://bgm.tv/user/101693
68是我打字打错了

**Comment by realsuxingyu** [comment]
这种404的用户大概有几千吧

**Comment by trim21** [comment]
用户id是mysql的自增id，不一定是连续的。

**Comment by realsuxingyu** [comment]
管理员……
净是403的错误怎么办
请求增大些并发量
感觉至少低了两个数量级
…… …… 请考虑下吧

**Comment by realsuxingyu** [comment]
[![xQldgS.md.jpg](https://s1.ax1x.com/2022/10/03/xQldgS.md.jpg)](https://imgse.com/i/xQldgS)
