### ISSUE TITLE
fetch 请求 PATCH 方法跨域问题

### ISSUE THREAD

**Issue by alanoy** [bangumi/api#172]
使用浏览器 fetch 修改收藏方法报错：

`Access to fetch at 'https://api.bgm.tv/v0/users/-/collections/375913' from origin 'http://localhost:3000' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.`

**Comment by trim21** [comment]
非幂等方法不支持跨域

**Comment by trim21** [comment]
https://github.com/bangumi/api/issues/157
