### ISSUE TITLE
修改收藏番剧完成度

### ISSUE THREAD

**Issue by ascrazy0** [bangumi/api#180]
所以目前只能用于修改书籍类条目的完成度吗

**Comment by trim21** [comment]
剧集条目可以通过另一个API直接修改剧集的收藏状态

**Comment by ascrazy0** [comment]
请问是哪一个

**Comment by ascrazy0** [comment]
> 剧集条目可以通过另一个API直接修改剧集的收藏状态

请问是哪一个

**Comment by trim21** [comment]
https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserSubjectEpisodeCollection

**Comment by ascrazy0** [comment]
好的解决了谢谢

> https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserSubjectEpisodeCollection
