### ISSUE TITLE
问题：Legacy API是不是用任何方法都无法读取里番了？

### ISSUE THREAD

**Issue by ruocaled** [bangumi/api#186]
比如
> GET https://api.bgm.tv/subject/389646

![Insomnia_2023-05-27_12-05-44](https://github.com/bangumi/api/assets/873853/01fcc941-5118-4726-874b-863767422bd7)

Token是  https://next.bgm.tv/demo/access-token 生成的，在v0 api中有效，可以获取里番。

我理解老API不再维护，只是想~垂死挣扎~确认一下。谢谢！

**Comment by trim21** [comment]
应该是这样
