### ISSUE TITLE
条目API 404 Not Found  问题

### ISSUE THREAD

**Issue by li-guohao** [bangumi/api#189]
我使用 https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/getSubjectById 调用，
换了好几个不是nsfw 的 subjectId 都是 404，（324，876，328609）
我的程序 [plugin-bgmtv](https://github.com/ikaros-dev/plugin-bgmtv/blob/master/src/main/java/run/ikaros/plugin/bgmtv/repository/BgmTvRepositoryImpl.java#L164) 里调用的也是 404.

API调用：
![image](https://github.com/bangumi/api/assets/46225881/e5c8c119-ff25-49fe-bef2-3b01ebf36215)

浏览器直接访问：
![image](https://github.com/bangumi/api/assets/46225881/7cb5e03d-3b2a-4659-83d0-0b62c7b44249)

程序里开不开代理都是一样的404，下面是程序运行的日志截图：
代码逻辑在：[plugin-bgmtv](https://github.com/ikaros-dev/plugin-bgmtv/blob/master/src/main/java/run/ikaros/plugin/bgmtv/repository/BgmTvRepositoryImpl.java#L164)

![image](https://github.com/bangumi/api/assets/46225881/ce3330a9-9349-4bba-9252-b1797613e208)

**Comment by trim21** [comment]
@Sai 修好了之后关下issue（

**Comment by li-guohao** [comment]
> @Sai 修好了之后关下issue（

我这边试了下还是一样的404

**Comment by trim21** [comment]
因为sai老板还没修吧...

**Comment by li-guohao** [comment]
我这边目前调用正常了，需要关闭掉这个issue吗？
