### ISSUE TITLE
https://bgm.tv/oauth/token_status 返回的 "expires" 是什么？

### ISSUE THREAD

**Issue by leohu1** [bangumi/api#192]
[查询授权信息](https://github.com/bangumi/api/blob/master/docs-raw/How-to-Auth.md#%E6%9F%A5%E8%AF%A2%E6%8E%88%E6%9D%83%E4%BF%A1%E6%81%AF)中返回的 expires 是什么意思？单位是什么？

**Comment by trim21** [comment]
https://bgm.tv/m/topic/group/385099#post_2414857
