### ISSUE TITLE
如何获得所有的收藏？现在支持返回25条？

### ISSUE THREAD

**Issue by huyumars** [bangumi/api#20]

**Comment by Sai** [comment]
获取全部收藏的 API 还没做完

**Comment by qdchenyixuan** [comment]
请问，获取评论只能20条有计划加上吗？谢谢

**Comment by Trim21** [comment]
https://bangumi.github.io/api/#/%E7%94%A8%E6%88%B7/get_user_collection_v0_users__username__collections_get
