### ISSUE TITLE
返回图片列分辨率分布不合理

### ISSUE THREAD

**Issue by yinvoke** [bangumi/api#200]
"images": {
                  "large": "http://lain.bgm.tv/pic/cover/l/bc/bc/378298_zO8ek.jpg",
                  "common": "http://lain.bgm.tv/pic/cover/c/bc/bc/378298_zO8ek.jpg",
                  "medium": "http://lain.bgm.tv/pic/cover/m/bc/bc/378298_zO8ek.jpg",
                  "small": "http://lain.bgm.tv/pic/cover/s/bc/bc/378298_zO8ek.jpg",
                  "grid": "http://lain.bgm.tv/pic/cover/g/bc/bc/378298_zO8ek.jpg"
              },
large有1.1mb，而其他的均不超过10kb，common，medium，small差距非常小且分辨率均非常低，目前为了清晰展示只能使用large，是否可以适当调整增大common和medium的分辨率大小以便于更合理的进行资源的使用

**Comment by trim21** [comment]
https://github.com/bangumi/img-proxy

有切图服务器，可以自行选择需要的分辨率大小
