### ISSUE TITLE
角色的人物接口返回图片皆为404

### ISSUE THREAD

**Issue by PhantomLGZ** [bangumi/api#201]
`v0/characters/{character_id}/persons`

测试：
`https://api.bgm.tv/v0/characters/133663/persons`

返回：
`[{"images":{"small":"https://lain.bgm.tv/r/100/pic/crt/l/e7/5b/391117_Fz2T4.jpg","grid":"https://lain.bgm.tv/r/200/pic/crt/l/e7/5b/391117_Fz2T4.jpg","large":"https://lain.bgm.tv/pic/crt/l/e7/5b/391117_Fz2T4.jpg","medium":"https://lain.bgm.tv/r/400/pic/crt/l/e7/5b/391117_Fz2T4.jpg"},"name":"加隈亜衣","subject_name":"異世界でもふもふなでなでするためにがんばってます。","subject_name_cn":"为了在异世界也能抚摸毛茸茸而努力","subject_id":391117,"staff":"主角","id":10806,"type":1}]`

任选图片皆404：
`https://lain.bgm.tv/r/100/pic/crt/l/e7/5b/391117_Fz2T4.jpg`

**Comment by trim21** [comment]
已修复
