### ISSUE TITLE
请问一下获取条目信息的api有限制访问频次么？

### ISSUE THREAD

**Issue by ru8lq0005** [bangumi/api#206]
个人是有需求去获取一下bangumi这边的动画中文名以及封面图片地址，大约6500条记录，为了避免并发之类的问题，因此在零点以后，做了5-10秒一个访问的循环调用，大概跑了十个小时，第二天发现有几十条数据因为字段问题存失败了，想重跑这二十条数据的时候发现UserAgent似乎被ban了，因为浏览器可以直接访问，但是通过本地跑起来的后端设置的ua访问就会connect ETIMEDOUT，因为后续每个季度动画更新的时候，可能都要补充获取个几十条记录，所以想问下官方对api访问的频次限制，大概是多少，我也可以避免类似的情况再次发生。

**Comment by Sai** [comment]
https://github.com/bangumi/Archive

条目数据有定期归档

**Comment by ru8lq0005** [comment]
> https://github.com/bangumi/Archive
> 
> 条目数据有定期归档

感谢，了解了
