### ISSUE TITLE
修改收藏 标签空集合报错

### ISSUE THREAD

**Issue by PhantomLGZ** [bangumi/api#207]
接口描述：`不传或者 null 都会被忽略，传 [] 则会删除所有 tag`
接口：`/v0/users/-/collections/{subject_id}`

测试：`https://api.bgm.tv/v0/users/-/collections/239258`
`{"comment":"","private":false,"rate":0,"tags":[],"type":1}`
返回：
`{"title":"Internal Server Error","details":{"error":"input contains invisible chars","path":"/v0/users/-/collections/239258","method":"POST"},"description":"Unexpected Internal Server Error"}`

测试：`https://api.bgm.tv/v0/users/-/collections/239258`
`{"comment":"","private":false,"rate":0,"tags":["a"],"type":1}`
请求通过，网页端`https://bangumi.tv/subject/239258`可查询到标签修改

**Comment by trim21** [comment]
已修复
