### ISSUE TITLE
Inconsistent item schema

### ISSUE THREAD

**Issue by alphatownsman** [bangumi/api#216]
https://api.bgm.tv/v0/subjects/37141
```
        {
            "key": "游戏类型",
            "value": "RPG"
        },
```

https://api.bgm.tv/v0/subjects/228086
```
        {
            "key": "游戏类型",
            "value": [
                {
                    "v": "ADV"
                },
                {
                    "v": "Psychological Horror"
                }
            ]
        },
```

Is this by design? how many varieties there? does this apply to all value field?

There seems not much detail on https://bangumi.github.io/api/ , appreciate some doc about this (and sorry if missed any)

**Comment by trim21** [comment]
Yes it's be degisn, although it's a bad degisn we should avoid in yhe future.

There are only 2 varieties
