### ISSUE TITLE
v0/subjects/{subject_id}/characters 返回的GRID字段可能有误

### ISSUE THREAD

**Issue by Predidit** [bangumi/api#226]
公开API返回的 grid 图片始终为分辨率略低的全身图片，而非头图。

私有API p1/subjects/{subject_id}/characters 返回的 gird 字段是正确的头图。

测试用例:

https://api.bgm.tv/v0/subjects/431767/characters

https://lain.bgm.tv/r/200/pic/crt/l/63/80/130664_crt_GdY10.jpg

https://next.bgm.tv/p1/subjects/431767/characters

https://lain.bgm.tv/pic/crt/g/63/80/130664_crt_GdY10.jpg

**Comment by trim21** [comment]
gird的图片应该revert回之前的行为来着 https://github.com/bangumi/server/issues/560

**Comment by Predidit** [comment]
也就是说这是一个已知的问题，不过还没有修复？

**Comment by trim21** [comment]
你可以PR（）

**Comment by trim21** [comment]
把这里改回之前的代码就行了 https://github.com/bangumi/server/blob/8e31b4093d2518c009de6a1d81a06ae595754382/web/res/image.go#L80
