### ISSUE TITLE
Public API 频繁返回500错误

### ISSUE THREAD

**Issue by Predidit** [bangumi/api#228]
在过去的12小时中，Public API 频繁波动，Private API 不受影响

**Comment by yangbot-tk** [comment]
+1

**Comment by Predidit** [comment]
问题似乎还是没有解决，API的失败率仍然很高。

看上去是 bangumi/server a5d5e62 导致的，也许我们可以暂时 revert 这一提交？

**Comment by yangbot-tk** [comment]
@trim21 请问这个问题是已经修复了吗？还是布署相关？我这边还可以复刻这个问题。例如GET Episodes

**Comment by trim21** [comment]
🤔 应该是 tag 的问题。现在应该ok了
