### ISSUE TITLE
/v0/me Get User 的 文档描述错误 "403 unauthorized" (?)

### ISSUE THREAD

**Issue by iamzhz** [bangumi/api#231]
在 [https://bangumi.github.io/api/#/%E7%94%A8%E6%88%B7/getMyself](https://bangumi.github.io/api/#/%E7%94%A8%E6%88%B7/getMyself) （/v0/me）的文档中，  
在 unauthorized 时的响应代码 **403 是否应为 401**?
<img width="741" alt="image" src="https://github.com/user-attachments/assets/f145f31e-1f0b-41df-ab66-ed2a75b0ac4f" />
在实际请求时，在请求未添加 access token 时的响应代码是 `401` , 返回内容是  
```python
{'title': 'Unauthorized', 'details': {'path': '/v0/me', 'method': 'GET'}, 'request_id': '8f16c4e2bc5f04f4-LHR',
'description': 'need Login'}
```
并且一般来说，403 是 Forbidden，401 是 unauthorized

**Comment by trim21** [comment]
应该是个文档的typo
