### ISSUE TITLE
无法批量更新章节状态

### ISSUE THREAD

**Issue by jokester** [bangumi/api#25]
POST `https://api.bgm.tv/ep/762301/status/watched`

HEADER: `{Accept: "application/json, text/plain, */*", Content-Type: "application/json;charset=utf-8", Authorization: "Bearer ***"}`

BODY: `{"ep_id":"762299,762300,762301"}`

得到 `{"request":"\/ep\/762301\/status\/watched","code":200,"error":"OK"}` 但只有 762301 这一个章节被更新了

**Comment by jokester** [comment]
header: `Content-Type: application/x-www-form-urlencoded`

body: `ep_id=762299,762300,762301`

也不行..不会了

**Comment by ainopara** [comment]
目前批量更新为 watched 是可以工作的。但是批量更新为 remove 似乎只有最后一个会被更新？

**Comment by Trim21** [comment]
有新API可以批量修改状态了
