### ISSUE TITLE
/user/:username/collection 没有应用默认cat=watching

### ISSUE THREAD

**Issue by markni** [bangumi/api#29]
访问 http://api.bgm.tv/user/1/collection 会返回空白html页面。
访问 http://api.bgm.tv/user/1/collection?cat=watching 没有问题。

[文档中](https://github.com/bangumi/api/blob/master/docs-raw/User-API.md#%E7%94%A8%E6%88%B7%E6%94%B6%E8%97%8F)标为：“默认为在看”

但[open API](https://github.com/bangumi/api/blob/master/open-api/api.yml#L35)显示cat没有default值，并且是required

但实际上也不是完全required，因为有`ids`被设置时不需要`cat`

**Comment by Trim21** [comment]
api 废弃
