### ISSUE TITLE
用api更新收藏状态后可能导致此条目不可见

### ISSUE THREAD

**Issue by jokester** [bangumi/api#31]
"不可见": 在web和api的返回中被算入总数，但不在列表中

此状态好像有机率在一定时间后变回正常，条件不明。下面截图的用户很久都没变。

<img width="484" alt="screenshot 2018-05-25 12 09 01" src="https://user-images.githubusercontent.com/802130/40524366-24d0e660-6015-11e8-96a1-87b7b29d2584.png">

**Comment by Sai** [comment]
这个计数有缓存，不会即时更新。

**Comment by jokester** [comment]
原来列表才是对的吗！

**Comment by BinotaLIU** [comment]
![image](https://user-images.githubusercontent.com/3190556/40538525-87b38c72-6044-11e8-850f-40bbc5f1d093.png)

我的所有收藏都是不可見的，也是全部被計入了

**Comment by jokester** [comment]
不对啊 我感觉计数是立刻更新的 列表才是延迟 (或永不) 更新
