### ISSUE TITLE
怎样获取自己的书籍条目的进度?

### ISSUE THREAD

**Issue by jokester** [bangumi/api#41]
更新进度好像是 [POST /subject/{subject_id}/update/watched_eps](https://bangumi.github.io/api/#/%E8%BF%9B%E5%BA%A6/post_subject__subject_id__update_watched_eps) 但是没找到获取已有进度的..

**Comment by feilongfl** [comment]
最近我在做[tachiyomi](https://github.com/inorichi/tachiyomi)的[track系统](https://github.com/inorichi/tachiyomi/pull/2032)，同样需要这个功能的API

论坛：https://bangumi.tv/group/topic/351043

希望能够添加

**Comment by Sai** [comment]
`/collection/{subject_id}` 接口增加了 `vol_status` 信息
