### ISSUE TITLE
/user/{username}/collection?ids={ids} 没有返回subject信息

### ISSUE THREAD

**Issue by kiiirzzz** [bangumi/api#51]
返回结果为
<pre>
{
    "subject_id":
        "id": int, // 3
        "type": string, // "doing"
        "name": string // "在看"
    },
}
</pre>
缺少subject的具体信息

参数中带responseGroup=medium / small / large 都是这样
已经带了app_id，请求头有token

**Comment by KIRI-Z** [comment]
另外，希望能增加 /user/{username}/collection?cat 时 responseGroup=large的结果

**Comment by Trim21** [comment]
api 废弃
