### ISSUE TITLE
移动版页面登录后重定向错误

### ISSUE THREAD

**Issue by OpportunityLiu** [bangumi/api#6]
![image](https://user-images.githubusercontent.com/13471233/36775900-d60c9466-1c9e-11e8-8768-03455a30d1e6.png)
桌面版登录成功后重定向
![image](https://user-images.githubusercontent.com/13471233/36775764-50a69aba-1c9e-11e8-932a-b13d8c2228aa.png)
移动版登录成功后重定向，location参数字符串错误

**Comment by Sai** [comment]
移动版登录页已与桌面版统一
