### ISSUE TITLE
在未登录情况下使用OAuth，当成功登录后丢失redirect_uri参数

### ISSUE THREAD

**Issue by ChengChung** [bangumi/api#7]
主要原因应该跳转到登录页面后，地址中chii_referer参数里没有带redirect_uri？
在OAuth中，redirect_uri在现在看来似乎是个必须的参数？

**Comment by Sai** [comment]
现在还有这个问题？

**Comment by ChengChung** [comment]
![Image](http://pic.joshu.moe/test.gif)

大概是这样，应该是还有这个问题吧（

**Comment by Sai** [comment]
这是因为你的 redirect_uri 和后台设置的不一致

**Comment by ChengChung** [comment]
那就没问题了。。之前一直没注意有这个设置框
