### ISSUE TITLE
关于/v0/subjects/{id}/persons 和 /v0/subjects/{id}/characters 的返回信息

### ISSUE THREAD

**Issue by syq1987** [bangumi/api#95]
我有个个人用的需求，想像 https://bangumi.tv/subject/1014/characters 这样通过subjectid，取得这条subject的所有characters的信息（主要是infobox以及关联cv）。
老的api   /subject/1014?responseGroup=large 能满足需求，但是取得的数据不全
v0的api  只能拿到部分信息，要拿全只能再逐条走/v0/persons/{id} 和/v0/characters/{id} 以及/v0/characters/{id}/persons，得几十次请求
有没有更好的方法

**Comment by Trim21** [comment]
https://github.com/bangumi/issues/issues/80 实时性不高的话等等这个？

**Comment by syq1987** [comment]
实时性不高，可以。thx

**Comment by Trim21** [comment]
那我就先close了

**Comment by Trim21** [comment]
https://github.com/bangumi/Archive/releases/tag/archive
